Repository cepdnaclk/e17-3yp-remote-medical-diagnostics, pull requests merged in 2021-08, with the labels that each got.

#11 added Project Timeline
  docs/README.md
  docs/images/gaant_chart.png
Labels: enhancement

#22 Sidebar implementation with routing
  src/front-end/public/index.html
  src/front-end/src/App.css
  src/front-end/src/App.tsx
  src/front-end/src/Login.test.tsx
  src/front-end/src/PatientHomeComponent.tsx
  src/front-end/src/Store.ts
  src/front-end/src/components/Login.tsx
  src/front-end/src/components/PatientMetaComponent.tsx
  src/front-end/src/components/dropdownMenu.tsx
  src/front-end/src/components/patient/PatientAppointments.tsx
  src/front-end/src/components/patient/PatientDoctors.tsx
  src/front-end/src/components/patient/PatientHome.tsx
  src/front-end/src/components/patient/PatientPayments.tsx
  src/front-end/src/components/sidebar.tsx
  src/front-end/src/components/sidebarItem.tsx
  src/front-end/src/globalStates/SidebarState.ts
  src/front-end/src/icons/appointment.svg
  src/front-end/src/icons/creditCard.svg
  src/front-end/src/icons/doctor.svg
  src/front-end/src/icons/expandIcon.svg
  src/front-end/src/icons/home.svg
  src/front-end/src/index.css
  src/front-end/src/index.tsx
  src/front-end/src/tests/Login.test.tsx
  src/front-end/src/tests/Sidebar.test.tsx
  src/front-end/src/tests/testUtils.tsx
Labels: enhancement

#26 :memo:Add UI Designs page
  docs/README.md
  docs/data/index.json
  docs/images/ui/ui1.png
  docs/images/ui/ui10.png
  docs/images/ui/ui11.png
  docs/images/ui/ui12.png
  docs/images/ui/ui13.png
  docs/images/ui/ui2.png
  docs/images/ui/ui3.png
  docs/images/ui/ui4.png
  docs/images/ui/ui5.png
  docs/images/ui/ui6.png
  docs/images/ui/ui7.png
  docs/images/ui/ui8.png
  docs/images/ui/ui9.png
  docs/ui_designs.md
Labels: documentation, enhancement

#32 📗 Update documentation
  docs/README.md
  src/back-end/README.md
  tests/README.md
Labels: documentation

#33 :construction:Implement search-doctor box in patient-home page
  src/front-end/src/App.css
  src/front-end/src/components/PatientMetaComponent.tsx
  src/front-end/src/components/patient/PatientHome.tsx
  src/front-end/src/components/patient/PatientHomeSearchDoctor.tsx
  src/front-end/src/icons/calendar.svg
  src/front-end/src/icons/globe.svg
  src/front-end/src/icons/person.svg
  src/front-end/src/icons/search.svg
  src/front-end/src/icons/specialization.svg
Labels: enhancement
